### PR TITLE
Background tasks are now ended in their expiration handler. Init method added to LocationShareModel class.

### PR DESCRIPTION
**Pull request by bonzoq**
The app never ran in the background longer then some 5 hours, because after that time there always was a background task that was not ended within 600 s on iOS 8, which caused the operating system to suspend the app. Now even if a background task does not end within the 600 s, it is force ended in its expiration handler. This way the app operates in the background forever. I've been testing it for over 24 hours now and it still operates in the background.

### CODE REVIEW

**Comment by bonzoq** [comment]
Init method was added to LocationShareModel class. The lack of this error may lead to errors when this code is ported as happened in my case.

**Comment by arielgelbard** [comment]
Thank you very much bonzoq for the solution!

**Comment by bonzoq** [comment]
No problem! Hope to see it merged sometime soon.

**Comment by StuartMorris0** [comment]
Has this been merged? should this be closed now? Thanks

**Pull request merged**
